/**
 * home-iot-api
 * The API for the EatBacon IOT project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.DeviceRegistrationInfo
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DeviceApi {

  /**
   * 
   * 
   * Expected answers:
   *   code 200 :  (successfully registered device)
   * 
   * @param device 
   */
  def register(device: Option[DeviceRegistrationInfo] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://dev-virtserver.swaggerhub.com/fabri-org/second-test-api/1.0.0", "/devices", "application/json")
      .withBody(device)
      .withSuccessResponse[Unit](200)
      

}

